backup old config files

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,9 +6,24 @@ check_if_installed(){
 	fi
 }
 
+backup_file(){
+	if [ -f ~/${1} ];
+	then
+		mv ~/${1} ./backup/${1} \
+			&& echo "moved old $1 to ./backup/$1" \
+			|| (echo "failed to backup ~/$1" \
+				&& exit 1)
+	fi	
+}
+
 check_if_installed zsh
 check_if_installed vim
 check_if_installed tmux
+
+mkdir ./backup
+backup_file .zshrc
+backup_file .tmux.conf
+backup_file .vimrc
 
 if ! [ -z "${SHELL##*zsh*}" ];
 	then
